build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21
  amd64:   ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21
  armhf:   ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.21
  armv7:   ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.21
  i386:    ghcr.io/home-assistant/i386-base-python:3.13-alpine3.21

squash: false
labels:
  io.hass.name: "SmartMarstek"
  io.hass.description: "Smart battery management for Marstek batteries"
  io.hass.arch: "aarch64|amd64"
  io.hass.type: "addon"
  io.hass.version: "1.19.71"
