apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    database: energy
    jsonData:
      version: Flux
      organization: marstek
      defaultBucket: energy
      tlsSkipVerify: false
    secureJsonData:
      token: marstek-influx-token-local
    editable: true
